### ISSUE TITLE
Tabs and coding style

### ISSUE THREAD

**Issue by troosh** [jgilje/v2m-player#3]
I suggest deleting all tabs in the project and taking a certain general style in order to simplify the subsequent fusion of branches.

In the original code, different tab stops were used in different files. But after the tabs are automatically expanded, you still need to edit the indents manually.

My experiments with clang-format showed that the original style is more like to the "Google" style.

I used this script (with subsequent manual editing):
[fix_style.sh.gz](https://github.com/jgilje/v2m-player/files/1610405/fix_style.sh.gz)

**Comment by troosh** [comment]
For example:
1) My expand tabs: 614e17e5cb506bdd790b6fbb8203fc0be60c7b5b
2) Fix formationg: ed80f30da49c09c7e10fdff40cc2cb0d2948cc9b

**Comment by jgilje** [comment]
Agreed, but I can't cleanly apply your commits because I've merged other PRs meanwhile (Ronan for example). 

If I where to apply your script to my repo now, wouldn't that make any future PRs from you even more harder to apply?

**Comment by troosh** [comment]
No, this well. I do not care how the problem with spaces can be solved. It's a pity only for my manual formatting, which I done for my convenience.

[The current difference between our repositories](https://github.com/jgilje/v2m-player/compare/jgilje:master...troosh:master#files_bucket) => It can be seen that most of the changes is formatting. And it hides significant code changes.

**Comment by zvezdochiot** [comment]
troosh.
You missed something.
The code has been completely cleared and optimized by Lion.
This moment you slipped through.

**Comment by troosh** [comment]
You are say about repository https://github.com/lieff/v2m-player?
But @jgilje has not yet merged commits from @lieff (look to https://github.com/lieff/v2m-player/network )

[The current difference between my and lieff repositories](https://github.com/jgilje/v2m-player/compare/jgilje:master...troosh:master#files_bucket) => Expand the diffs between the repositories of the file synth_core.cpp and learn a lot of new things...

**Comment by zvezdochiot** [comment]
troosh.
Lion did not give a request for a merger.
I could not merge with him for ideological reasons.
But I managed to borrow the code for my needs.
Testing has yielded good results. The code was accepted.
In your code, the formatting is the same as for Lion.

**Comment by lieff** [comment]
Hmm. I did my own port for https://github.com/lieff/lvg ("update" commit represent merge with my port) so, I adjust code style as used here. I can make PR if someone need this changes. Also I found some errors. One I remember:
```
+    {
+        // performs 64bit (nexttime-time)*usecs/td2 and a 32.32bit addition to smpldelta:smplrem
         uint64_t t = ((nexttime - time) * (uint64_t) usecs) / td2;
         uint32_t r = *smplrem;
-        *smplrem += (t >> 32);          // bits 32-63
+        *smplrem   += (t >> 32);        // bits 32-63
         *smpldelta += (t & 0xffffffff); // bits 00-31
-        if (*smplrem < r) {
-            *smpldelta++;
+        if (*smplrem < r)
+        {
+            *smpldelta += 1;
         }
-	}
+    }
```
++ have higher priority than *.

**Comment by troosh** [comment]
I'm found this bug by __cppcheck__, too:

`[v2mplayer.cpp:50]: (warning) Ineffective statement similar to '*A++;'. Did you intend to write '(*A)++;'?`

And my fix is c766a6a5e8416e9b69deee818a5457986a00bda2

**Comment by zvezdochiot** [comment]
cppcheck -v --enable=all v2mplayer.cpp
Checking v2mplayer.cpp...
[v2mplayer.h:24]: (style) The class 'V2MPlayer 'does not have a constructor but it has attributes. The attributes are not initialized which may cause bugs or undefined behavior.
Checking v2mplayer.cpp: V2MPLAYER_SYNC_FUNCTIONS...
Checking v2mplayer.cpp: __cplusplus...
Checking usage of global functions..
